[2023-06-16T20:28:23.474+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.executor_task scheduled__2023-06-16T19:00:00+00:00 [queued]>
[2023-06-16T20:28:23.682+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.executor_task scheduled__2023-06-16T19:00:00+00:00 [queued]>
[2023-06-16T20:28:23.683+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2023-06-16T20:28:24.437+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): executor_task> on 2023-06-16 19:00:00+00:00
[2023-06-16T20:28:24.446+0000] {standard_task_runner.py:57} INFO - Started process 600 to run task
[2023-06-16T20:28:24.451+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'executor_task', 'scheduled__2023-06-16T19:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag.py', '--cfg-path', '/tmp/tmpjdz3rhjw']
[2023-06-16T20:28:24.455+0000] {standard_task_runner.py:85} INFO - Job 83: Subtask executor_task
[2023-06-16T20:28:26.043+0000] {task_command.py:410} INFO - Running <TaskInstance: demo_dag.executor_task scheduled__2023-06-16T19:00:00+00:00 [running]> on host 92863fbca0bd
[2023-06-16T20:28:27.443+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-16T20:28:28.883+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='personaltraingcp@gmail.com' AIRFLOW_CTX_DAG_OWNER='Leyner_Bejarano' AIRFLOW_CTX_DAG_ID='demo_dag' AIRFLOW_CTX_TASK_ID='executor_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-16T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-16T19:00:00+00:00'
[2023-06-16T20:28:30.030+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-16T20:28:30.031+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \n        cd /opt/***/dags/scripts &&\n        pip install -r requirements.txt &&\n        python lambdaExecutor.py -dt 2023-06-16 -dh 19 -q https://sqs.us-east-2.amazonaws.com/147929168898/lokaInterviewSQS -ak AKIASE4KD7QBGVHE4G7U -sk AKIASE4KD7QBGVHE4G7U &&\n        pip freeze\n        ']
[2023-06-16T20:28:30.371+0000] {subprocess.py:86} INFO - Output:
[2023-06-16T20:29:00.131+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-06-16T20:29:04.352+0000] {subprocess.py:93} INFO - Collecting boto3==1.26.151 (from -r requirements.txt (line 1))
[2023-06-16T20:29:04.483+0000] {subprocess.py:93} INFO -   Downloading boto3-1.26.151-py3-none-any.whl (135 kB)
[2023-06-16T20:29:04.587+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.6/135.6 kB 1.3 MB/s eta 0:00:00
[2023-06-16T20:29:06.714+0000] {subprocess.py:93} INFO - Collecting botocore==1.29.151 (from -r requirements.txt (line 2))
[2023-06-16T20:29:06.749+0000] {subprocess.py:93} INFO -   Downloading botocore-1.29.151-py3-none-any.whl (10.9 MB)
[2023-06-16T20:29:13.673+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 1.5 MB/s eta 0:00:00
[2023-06-16T20:29:14.708+0000] {subprocess.py:93} INFO - Collecting fastavro==1.7.4 (from -r requirements.txt (line 3))
[2023-06-16T20:29:14.746+0000] {subprocess.py:93} INFO -   Downloading fastavro-1.7.4-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
[2023-06-16T20:29:15.680+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 2.6 MB/s eta 0:00:00
[2023-06-16T20:29:15.695+0000] {subprocess.py:93} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (1.3.5)
[2023-06-16T20:29:15.697+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil==2.8.2 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.8.2)
[2023-06-16T20:29:15.698+0000] {subprocess.py:93} INFO - Requirement already satisfied: pytz==2023.3 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (2023.3)
[2023-06-16T20:29:15.700+0000] {subprocess.py:93} INFO - Requirement already satisfied: s3transfer==0.6.1 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (0.6.1)
[2023-06-16T20:29:15.701+0000] {subprocess.py:93} INFO - Requirement already satisfied: six==1.16.0 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (1.16.0)
[2023-06-16T20:29:16.223+0000] {subprocess.py:93} INFO - Collecting tzdata==2023.3 (from -r requirements.txt (line 9))
[2023-06-16T20:29:16.291+0000] {subprocess.py:93} INFO -   Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
[2023-06-16T20:29:16.779+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 695.0 kB/s eta 0:00:00
[2023-06-16T20:29:17.359+0000] {subprocess.py:93} INFO - Collecting urllib3==1.26.16 (from -r requirements.txt (line 10))
[2023-06-16T20:29:17.391+0000] {subprocess.py:93} INFO -   Downloading urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
[2023-06-16T20:29:17.733+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.1/143.1 kB 397.9 kB/s eta 0:00:00
[2023-06-16T20:29:18.228+0000] {subprocess.py:93} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (0.10.0)
[2023-06-16T20:29:20.099+0000] {subprocess.py:93} INFO - Requirement already satisfied: numpy>=1.17.3 in /home/***/.local/lib/python3.7/site-packages (from pandas->-r requirements.txt (line 4)) (1.21.6)
[2023-06-16T20:29:52.440+0000] {subprocess.py:93} INFO - Installing collected packages: urllib3, tzdata, fastavro, botocore, boto3
[2023-06-16T20:29:52.440+0000] {subprocess.py:93} INFO -   Attempting uninstall: urllib3
[2023-06-16T20:29:52.446+0000] {subprocess.py:93} INFO -     Found existing installation: urllib3 1.26.15
[2023-06-16T20:29:52.472+0000] {subprocess.py:93} INFO -     Uninstalling urllib3-1.26.15:
[2023-06-16T20:29:52.544+0000] {subprocess.py:93} INFO - ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'LICENSE.txt'
[2023-06-16T20:29:52.545+0000] {subprocess.py:93} INFO - 
[2023-06-16T20:29:53.580+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-16T20:29:53.854+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-16T20:29:54.094+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=demo_dag, task_id=executor_task, execution_date=20230616T190000, start_date=20230616T202823, end_date=20230616T202954
[2023-06-16T20:29:54.756+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 83 for task executor_task (Bash command failed. The command returned a non-zero exit code 1.; 600)
[2023-06-16T20:29:54.828+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-16T20:29:54.856+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
