[2023-06-16T21:23:08.584+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.executor_task scheduled__2023-06-16T20:00:00+00:00 [queued]>
[2023-06-16T21:23:08.714+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.executor_task scheduled__2023-06-16T20:00:00+00:00 [queued]>
[2023-06-16T21:23:08.715+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 4
[2023-06-16T21:23:08.775+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): executor_task> on 2023-06-16 20:00:00+00:00
[2023-06-16T21:23:08.792+0000] {standard_task_runner.py:57} INFO - Started process 671 to run task
[2023-06-16T21:23:08.801+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'executor_task', 'scheduled__2023-06-16T20:00:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag.py', '--cfg-path', '/tmp/tmpzvinvf1p']
[2023-06-16T21:23:08.805+0000] {standard_task_runner.py:85} INFO - Job 95: Subtask executor_task
[2023-06-16T21:23:08.932+0000] {task_command.py:410} INFO - Running <TaskInstance: demo_dag.executor_task scheduled__2023-06-16T20:00:00+00:00 [running]> on host 03b5ffc5bbd5
[2023-06-16T21:23:09.151+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-16T21:23:09.211+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='personaltraingcp@gmail.com' AIRFLOW_CTX_DAG_OWNER='Leyner_Bejarano' AIRFLOW_CTX_DAG_ID='demo_dag' AIRFLOW_CTX_TASK_ID='executor_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-16T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-16T20:00:00+00:00'
[2023-06-16T21:23:09.212+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-16T21:23:09.213+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \n        cd /opt/***/dags/scripts &&\n        pip install -r requirements.txt &&\n        python lambdaExecutor.py -dt 2023-06-16 -dh 20 -q https://sqs.us-east-2.amazonaws.com/147929168898/lokaInterviewSQS -ak AKIASE4KD7QBGVHE4G7U -sk AKIASE4KD7QBGVHE4G7U &&\n        pip freeze\n        ']
[2023-06-16T21:23:09.289+0000] {subprocess.py:86} INFO - Output:
[2023-06-16T21:23:11.665+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-06-16T21:23:14.621+0000] {subprocess.py:93} INFO - Requirement already satisfied: boto3==1.26.151 in /home/***/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.26.151)
[2023-06-16T21:23:14.756+0000] {subprocess.py:93} INFO - Requirement already satisfied: botocore<1.30.0,>=1.29.151 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (1.29.151)
[2023-06-16T21:23:14.757+0000] {subprocess.py:93} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (0.10.0)
[2023-06-16T21:23:14.759+0000] {subprocess.py:93} INFO - Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /home/***/.local/lib/python3.7/site-packages (from boto3==1.26.151->-r requirements.txt (line 1)) (0.6.1)
[2023-06-16T21:23:14.809+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.7/site-packages (from botocore<1.30.0,>=1.29.151->boto3==1.26.151->-r requirements.txt (line 1)) (2.8.2)
[2023-06-16T21:23:14.810+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.7/site-packages (from botocore<1.30.0,>=1.29.151->boto3==1.26.151->-r requirements.txt (line 1)) (1.26.16)
[2023-06-16T21:23:14.880+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.30.0,>=1.29.151->boto3==1.26.151->-r requirements.txt (line 1)) (1.16.0)
[2023-06-16T21:24:28.663+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-16T21:24:28.769+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-16T21:24:28.857+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=demo_dag, task_id=executor_task, execution_date=20230616T200000, start_date=20230616T212308, end_date=20230616T212428
[2023-06-16T21:24:29.013+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 95 for task executor_task (Bash command failed. The command returned a non-zero exit code 1.; 671)
[2023-06-16T21:24:29.039+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-16T21:24:29.065+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
